# Snapcraft build recipe
#
# Reference:
#
# * The snapcraft format | Snapcraft documentation
#   https://snapcraft.io/docs/snapcraft-format
#
# Copyright 2021 林博仁(Buo-ren, Lin) <Buo.Ren.Lin@gmail.com>
# SPDX-License-Identifier: CC-BY-SA-4.0
name: sommelier-hook-speedup-poc
base: core18
version: git
summary: Speed-up Wine snaps first launch time
description: |
  Cut down first launch time by doing the Wine initialization process during snap install using Snapd's hook mechanism.

grade: devel
confinement: strict

# Wine snaps are only buildable on these platforms
architectures:
  - build-on: amd64
  - build-on: i386

parts:
  sommelier-core:
    plugin: make
    source: https://github.com/snapcrafters/sommelier-core.git
    source-branch: '1.0'

  hooks:
    source: snap/local/hooks
    plugin: dump
    organize:
      configure: snap/hooks/configure

  xvfb:
    plugin: nil
    stage-packages:
      # For mcookie(1) command, somehow it isn't included in an X
      # package, the one that is included in the core snap isn't
      # accessible through the confinement
      - util-linux

      - xvfb

plugs:
  wine-runtime:
    interface: content
    target: $SNAP/wine-runtime
    default-provider: wine-platform-runtime
  wine-5-stable:
    interface: content
    target: $SNAP/wine-platform
    default-provider: wine-platform-5-stable

apps:
  sommelier-hook-speedup-poc:
    extensions:
      - gnome-3-28
    command: bin/sommelier run-exe
    environment:
      RUN_EXE: winecfg

      # Prevent pop-ups about Wine Mono and Wine Gecko
      WINEDLLOVERRIDES: '$WINEDLLOVERRIDES;mscoree,mshtml='

    plugs:
      - home
      - network
      - network-bind
  wine:
    extensions:
      - gnome-3-28
    command: bin/sommelier
    plugs:
      - home
      - network
  winetricks:
    extensions:
      - gnome-3-28
    command: bin/sommelier winetricks
    plugs:
      - home
      - network

hooks:
  configure:
    plugs:
      - desktop
      - network-bind
      - x11
